export enum OrderStatus {
  ACCEPTED = 'ACCEPTED',
  WAITING_FOR_INPUT = 'WAITING_FOR_INPUT',
  SUBMITTED = 'SUBMITTED',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
  CANCELLED = 'CANCELLED',
}
